version: "3.8"

services:
  webapp:
    image: "cloud-teknix:latest"
    container_name: cloud-teknix
    ports:
      - "2001:2001"   # port backend express
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: "unless-stopped"